spring:
  datasource:
    url: jdbc:h2:mem:fixmybudget;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  config:
    import: classpath:/statement-properties.yml
  liquibase:
    change-log: classpath:/database/changelogs/changelog-master.yml
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org.springframework.graphql: DEBUG
      org.springframework.web: DEBUG
